// <auto-generated />
namespace email2sms.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class TrackSids : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TrackSids));
        
        string IMigrationMetadata.Id
        {
            get { return "201507220044046_TrackSids"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
